package models

// AuthChallenge — nonce generated by backend to be signed by client
type AuthChallenge struct {
	Challenge string `json:"challenge"` // "bj_auth_<timestamp>_<random_hex>"
	ExpiresAt int64  `json:"expires_at"` // Unix timestamp — valid for 5 minutes
}

// AuthSession — session created after successful login
type AuthSession struct {
	Token        string `json:"token"`              // Bearer token (random 32 byte hex)
	PlayerID     string `json:"player_id"`          // Nimiq address
	NimiqAddress string `json:"nimiq_address"`
	DeviceID     string `json:"device_id,omitempty"` // optional device identifier (64-char hex)
	CreatedAt    int64  `json:"created_at"`
	ExpiresAt    int64  `json:"expires_at"`
}