#!/usr/bin/env python3
"""
build — Split oversized Godot WebAssembly exports and finish the export
folder for Cloudflare Pages.

Cloudflare Pages rejects individual files over 25 MiB. Godot's exported
.wasm often blows past that on its own, so instead of compressing it we
just cut it in half:

For every .wasm file found that's larger than SPLIT_THRESHOLD_BYTES:
  1. Splits it into two files sitting next to it: <name>.wasm.part1 and
     <name>.wasm.part2 (each comfortably under the size limit).
  2. Deletes the original .wasm — it no longer exists as a single file
     on disk, so it can never be served (and rejected) as one big blob.

Then:
  - Writes wasm-loader.js into the export folder. It patches
    window.fetch so that when Godot's engine asks for the original
    "index.wasm", the loader instead fetches both .part1/.part2 files,
    concatenates the bytes, and hands back a normal-looking Response —
    Godot never knows the file was split.
  - Injects <script src="wasm-loader.js"></script> as the very first
    script in index.html's <head>, so it patches fetch before Godot's
    own loader script runs (idempotent — safe to re-run).

Then copies the deploy-time extras from game/template into the export
folder:
  - _headers
  - assets/ (whole folder)

Finally it fills in the URL placeholders. Nothing in this project hardcodes
a domain: game/template's index.html, robots.txt and sitemap.xml all carry
__GAME_URL__ / __API_BASE__ markers, and this script replaces them with the
values from setup/urls.ini (the single source of truth — see also
setup/apply_urls.py, which pushes the same values into ApiConfig.gd before
the export). If any placeholder is left unresolved afterwards, this script
fails loudly rather than shipping a broken build.

Usage:
  python build.py                 # auto-finds ../export (relative to this script)
  python build.py path/to/folder  # explicit override
"""
import sys, shutil, pathlib

# urls_config.py sits next to this file. Python normally puts the script's own
# folder on sys.path automatically, but not under every launcher (`-m`, some
# IDE run configs, embedded interpreters), so make it explicit — this script
# gets invoked from devtools and by hand from several different cwds.
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))

from urls_config import (
    API_BASE_PLACEHOLDER,
    GAME_URL_PLACEHOLDER,
    load_urls_or_exit,
)

# Cloudflare Pages' hard per-file limit is 25 MiB. We split anything
# bigger than this, with a little headroom so each half stays safely
# under the limit even for large files.
SPLIT_THRESHOLD_BYTES = 24 * 1024 * 1024  # 24 MiB

LOADER_FILENAME = "wasm-loader.js"

# The export folder this script looks in by default: a sibling-level
# "export" folder one directory up from wherever this script lives
# (i.e. this script sits in some inner folder, "export" is next to
# that folder's parent — NOT relative to the current working directory,
# so it works the same no matter where you call it from).
DEFAULT_EXPORT_DIRNAME = "export"

# Where the deploy-time extras (_headers, assets/) live, relative to
# this script's own directory.
TEMPLATE_DIRNAME = pathlib.Path("game") / "template"


def split_file(path: pathlib.Path) -> tuple[pathlib.Path, pathlib.Path]:
    """Splits `path` into two roughly-equal halves next to it and
    deletes the original. Returns the two new paths."""
    data = path.read_bytes()
    midpoint = len(data) // 2

    part1 = path.parent / (path.name + ".part1")
    part2 = path.parent / (path.name + ".part2")
    part1.write_bytes(data[:midpoint])
    part2.write_bytes(data[midpoint:])

    path.unlink()

    for part in (part1, part2):
        size_mb = part.stat().st_size / 1e6
        flag = " (still over 25MB!)" if part.stat().st_size > SPLIT_THRESHOLD_BYTES else ""
        print(f"  wrote  → {part.name}  ({size_mb:.1f} MB){flag}")
    print(f"  deleted original {path.name}")

    return part1, part2


def write_loader_script(export_folder: pathlib.Path, split_filenames: list[str]):
    """Writes wasm-loader.js, which patches window.fetch to reassemble
    any wasm file named in split_filenames from its .part1/.part2
    pieces before Godot's engine ever sees it."""
    names_js = ", ".join(f'"{name}"' for name in split_filenames)
    loader_src = f"""\
// Auto-generated by build.py — do not edit by hand.
//
// Some .wasm exports were split into two files to stay under
// Cloudflare Pages' 25MB per-file limit. This patches window.fetch so
// that when Godot's engine requests one of those files, it instead
// fetches the two .part1/.part2 halves and hands back a normal-looking
// Response — Godot never knows the file was split.
//
// MEMORY: the two halves are stitched together via a ReadableStream that
// re-emits each part's chunks as they arrive, sequentially — this file's
// bytes are never fully buffered in this script's own memory (previously
// this awaited both parts' arrayBuffer() and concatenated them into one
// new same-size Uint8Array, meaning 3 full copies of the wasm — part1 +
// part2 + combined — briefly coexisted in memory at the exact moment the
// download finished, right before WASM compile/instantiate even started.
// On low-RAM devices/older phones that peak was enough to get the tab's
// process killed for OOM right after "100% loaded", which some WebView
// hosts recover from by silently reloading the page — looking like an
// infinite reload loop with no visible error). Streaming also lets
// Godot's own loader use WebAssembly.instantiateStreaming if it does,
// compiling as bytes arrive instead of needing the whole file resident
// in memory first.
//
// Falls back to the old buffer-concat approach if ReadableStream (or the
// Response-from-stream constructor) isn't available — belt and suspenders
// for any engine/browser combination this hasn't been tested against.
//
// IMPORTANT: this script must load and run BEFORE Godot's own
// engine/loader script (index.js). build.py inserts it as the first
// <script> tag in <head> for exactly that reason.
(function () {{
  var SPLIT_FILES = [{names_js}];
  var originalFetch = window.fetch.bind(window);
  var supportsStreamingResponse = (typeof ReadableStream !== "undefined");

  function combineViaBuffers(r1, r2) {{
    return Promise.all([r1.arrayBuffer(), r2.arrayBuffer()]).then(function (buffers) {{
      var b1 = buffers[0], b2 = buffers[1];
      var combined = new Uint8Array(b1.byteLength + b2.byteLength);
      combined.set(new Uint8Array(b1), 0);
      combined.set(new Uint8Array(b2), b1.byteLength);
      return new Response(combined, {{
        status: 200,
        headers: {{ "Content-Type": "application/wasm" }}
      }});
    }});
  }}

  function combineViaStream(r1, r2) {{
    var len1 = parseInt(r1.headers.get("Content-Length") || "0", 10);
    var len2 = parseInt(r2.headers.get("Content-Length") || "0", 10);
    var totalLen = (len1 && len2) ? (len1 + len2) : null;

    var stream = new ReadableStream({{
      start: function (controller) {{
        var reader1 = r1.body.getReader();
        function pump1() {{
          return reader1.read().then(function (res) {{
            if (res.done) return pump2start();
            controller.enqueue(res.value);
            return pump1();
          }});
        }}
        function pump2start() {{
          var reader2 = r2.body.getReader();
          function pump2() {{
            return reader2.read().then(function (res) {{
              if (res.done) {{ controller.close(); return; }}
              controller.enqueue(res.value);
              return pump2();
            }});
          }}
          return pump2();
        }}
        pump1().catch(function (e) {{ controller.error(e); }});
      }}
    }});

    var headers = {{ "Content-Type": "application/wasm" }};
    if (totalLen) headers["Content-Length"] = String(totalLen);
    return new Response(stream, {{ status: 200, headers: headers }});
  }}

  window.fetch = function (input, init) {{
    var url = typeof input === "string" ? input : input.url;
    var filename = url.split("/").pop().split("?")[0];

    if (SPLIT_FILES.indexOf(filename) === -1) {{
      return originalFetch(input, init);
    }}

    return Promise.all([
      originalFetch(url + ".part1", init),
      originalFetch(url + ".part2", init),
    ]).then(function (responses) {{
      var r1 = responses[0], r2 = responses[1];
      if (!r1.ok || !r2.ok) {{
        throw new Error("wasm-loader: failed to fetch parts for " + filename);
      }}
      if (supportsStreamingResponse) {{
        try {{
          return combineViaStream(r1, r2);
        }} catch (e) {{
          // Fall through to buffered combine below with the same responses
          // only if their bodies haven't been consumed yet — combineViaStream
          // throws synchronously (before touching .body) on unsupported
          // engines, so this is safe.
          return combineViaBuffers(r1, r2);
        }}
      }}
      return combineViaBuffers(r1, r2);
    }});
  }};
}})();
"""
    out = export_folder / LOADER_FILENAME
    out.write_text(loader_src, encoding="utf-8")
    print(f"  wrote  → {out}")


def inject_loader_into_html(export_folder: pathlib.Path):
    """Inserts <script src="wasm-loader.js"></script> as the first
    thing in <head>, so it runs before Godot's own loader script.
    Safe to re-run — won't duplicate the tag."""
    html_candidates = list(export_folder.glob("*.html"))
    if not html_candidates:
        print("  no .html file found in export folder — couldn't inject loader tag, "
              "add <script src=\"wasm-loader.js\"></script> as the FIRST script in <head> manually.")
        return

    html_path = html_candidates[0]
    text = html_path.read_text(encoding="utf-8")

    tag = f'<script src="{LOADER_FILENAME}"></script>'
    if tag in text:
        print(f"  {html_path.name} already has the loader tag, skipping injection")
        return

    if "<head>" in text:
        text = text.replace("<head>", f"<head>\n    {tag}", 1)
    else:
        print(f"  couldn't find <head> in {html_path.name} — add {tag} manually as the "
              f"first script tag.")
        return

    html_path.write_text(text, encoding="utf-8")
    print(f"  injected {tag} into {html_path.name}")


def find_default_export_folder() -> pathlib.Path:
    """
    Look for an "export" folder one level up from this script's own
    directory, e.g.:
        NimJump/
        ├── export/          <- target
        └── tools/
            └── build.py
    Falls back to searching one level up from the current working
    directory if the script-relative guess doesn't exist, so it still
    works if the script gets copied around.
    """
    script_dir = pathlib.Path(__file__).resolve().parent
    candidate = script_dir.parent / DEFAULT_EXPORT_DIRNAME
    if candidate.is_dir():
        return candidate
    cwd_candidate = pathlib.Path.cwd().parent / DEFAULT_EXPORT_DIRNAME
    if cwd_candidate.is_dir():
        return cwd_candidate
    # Nothing found — return the primary guess anyway so the error
    # message below tells the user exactly where it looked.
    return candidate


def find_template_folder() -> pathlib.Path:
    """
    Look for game/template one level up from this script's own
    directory (same base as find_default_export_folder), falling back
    to the current working directory's parent if that doesn't exist.
    """
    script_dir = pathlib.Path(__file__).resolve().parent
    candidate = script_dir.parent / TEMPLATE_DIRNAME
    if candidate.is_dir():
        return candidate
    cwd_candidate = pathlib.Path.cwd().parent / TEMPLATE_DIRNAME
    if cwd_candidate.is_dir():
        return cwd_candidate
    return candidate


def substitute_urls(text: str, api_base: str, game_url: str) -> str:
    """Swaps the two placeholders for their real values. One helper for every
    file type so the marker names can never drift apart between them."""
    return (text
            .replace(GAME_URL_PLACEHOLDER, game_url)
            .replace(API_BASE_PLACEHOLDER, api_base))


def copy_with_urls(src: pathlib.Path, dst: pathlib.Path, api_base: str, game_url: str) -> int:
    """Copies a text file while substituting URL placeholders. Returns how
    many placeholder occurrences were replaced (0 is fine — not every file
    has to contain one)."""
    text = src.read_text(encoding="utf-8")
    count = text.count(GAME_URL_PLACEHOLDER) + text.count(API_BASE_PLACEHOLDER)
    dst.write_text(substitute_urls(text, api_base, game_url), encoding="utf-8")
    return count


def fill_urls_in_export_html(export_folder: pathlib.Path, api_base: str, game_url: str):
    """Replaces the placeholders inside the ALREADY-EXPORTED index.html.

    Godot copies game/template/index.html into export/ verbatim during the
    web export, placeholders and all — this is where the canonical/OG/Twitter/
    JSON-LD tags and the client-log API base actually get their real values.
    Idempotent: once substituted there are no markers left, so re-running is a
    no-op.
    """
    html_files = list(export_folder.glob("*.html"))
    if not html_files:
        print("  no .html file found in export folder — nothing to substitute")
        return

    for html_path in html_files:
        text = html_path.read_text(encoding="utf-8")
        count = text.count(GAME_URL_PLACEHOLDER) + text.count(API_BASE_PLACEHOLDER)
        if count == 0:
            print(f"  {html_path.name}: no placeholders left (already substituted)")
            continue
        html_path.write_text(substitute_urls(text, api_base, game_url), encoding="utf-8")
        print(f"  {html_path.name}: filled {count} placeholder(s)")


def verify_no_placeholders_left(export_folder: pathlib.Path):
    """Last line of defence: scan every text file we're about to ship for a
    leftover marker. A stray __GAME_URL__ in a canonical tag or in the API
    base would be live on the deployed site, so this is a hard failure rather
    than a warning."""
    offenders = []
    for path in sorted(export_folder.rglob("*")):
        if not path.is_file() or path.suffix.lower() not in (".html", ".txt", ".xml", ".json", ".js"):
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except (UnicodeDecodeError, OSError):
            continue
        if GAME_URL_PLACEHOLDER in text or API_BASE_PLACEHOLDER in text:
            offenders.append(path.relative_to(export_folder))

    if offenders:
        print("\nUNRESOLVED URL PLACEHOLDERS — not safe to deploy:", file=sys.stderr)
        for rel in offenders:
            print(f"  {rel}", file=sys.stderr)
        print("\n  These files still contain __GAME_URL__ / __API_BASE__.\n"
              "  Check setup/urls.ini and re-run this script.\n", file=sys.stderr)
        sys.exit(1)

    print("  no leftover placeholders — URLs are fully resolved")


def copy_template_extras(export_folder: pathlib.Path, template_folder: pathlib.Path,
                         api_base: str, game_url: str):
    """
    Copies _headers, manifest.json, robots.txt, sitemap.xml, and assets/
    from game/template into the export folder, overwriting whatever is
    already there. robots.txt and sitemap.xml go through URL substitution
    on the way.
    """
    if not template_folder.is_dir():
        print(f"Template folder not found: {template_folder.resolve()}")
        print("  Skipping _headers/manifest.json/robots.txt/sitemap.xml/assets copy — check the game/template path.")
        return

    headers_src = template_folder / "_headers"
    if headers_src.is_file():
        headers_dst = export_folder / "_headers"
        shutil.copyfile(headers_src, headers_dst)
        print(f"  copied _headers → {headers_dst}")
    else:
        print(f"  no _headers found in {template_folder.resolve()}, skipped")

    # manifest.json — Web App Manifest, used by Nimiq Pay's mini-app list
    # (and any "add to home screen" flow) to source the game's icon. index.html
    # links this via <link rel="manifest">; that link only works if the file
    # actually made it into the export folder, hence copying it here same as
    # _headers/assets.
    manifest_src = template_folder / "manifest.json"
    if manifest_src.is_file():
        manifest_dst = export_folder / "manifest.json"
        shutil.copyfile(manifest_src, manifest_dst)
        print(f"  copied manifest.json → {manifest_dst}")
    else:
        print(f"  no manifest.json found in {template_folder.resolve()}, skipped")

    # robots.txt / sitemap.xml — SEO. Search engine crawlers request these
    # from the domain root (https://.../robots.txt), so they have to land in
    # export/'s top level same as everything else here, not just live in the
    # source template folder.
    for seo_name in ("robots.txt", "sitemap.xml"):
        seo_src = template_folder / seo_name
        if seo_src.is_file():
            seo_dst = export_folder / seo_name
            filled = copy_with_urls(seo_src, seo_dst, api_base, game_url)
            suffix = f" ({filled} URL placeholder(s) filled)" if filled else ""
            print(f"  copied {seo_name} → {seo_dst}{suffix}")
        else:
            print(f"  no {seo_name} found in {template_folder.resolve()}, skipped")

    assets_src = template_folder / "assets"
    if assets_src.is_dir():
        assets_dst = export_folder / "assets"
        if assets_dst.exists():
            shutil.rmtree(assets_dst)
        shutil.copytree(assets_src, assets_dst)
        print(f"  copied assets/ → {assets_dst}")
    else:
        print(f"  no assets/ folder found in {template_folder.resolve()}, skipped")


def main():
    # Loaded up front: a missing/broken urls.ini should stop the build before
    # anything is written, not halfway through.
    api_base, game_url = load_urls_or_exit()

    if len(sys.argv) > 1:
        folder = pathlib.Path(sys.argv[1])
    else:
        folder = find_default_export_folder()
        print(f"No path given — looking for '{DEFAULT_EXPORT_DIRNAME}' folder: {folder.resolve()}\n")

    if not folder.is_dir():
        print(f"Folder not found: {folder.resolve()}")
        print(f"Pass an explicit path instead: python {pathlib.Path(__file__).name} path/to/export/folder")
        sys.exit(1)

    files = [w for w in sorted(folder.rglob("*.wasm")) if not w.name.endswith(".opt.wasm")]
    if not files:
        print(f"No .wasm files found in {folder.resolve()}")
        sys.exit(1)

    print(f"Found {len(files)} .wasm file(s) in {folder.resolve()}:\n")

    split_filenames = []
    for wasm in files:
        size_mb = wasm.stat().st_size / 1e6
        print(f"[{wasm.name}]  ({size_mb:.1f} MB)")

        if wasm.stat().st_size <= SPLIT_THRESHOLD_BYTES:
            print(f"  under {SPLIT_THRESHOLD_BYTES/1e6:.0f}MB, leaving as-is")
        else:
            split_file(wasm)
            split_filenames.append(wasm.name)
        print()

    if split_filenames:
        print("Writing wasm-loader.js and wiring it into index.html:\n")
        write_loader_script(folder, split_filenames)
        inject_loader_into_html(folder)
        print()
    else:
        print("No files needed splitting — skipping wasm-loader.js.\n")

    template_folder = find_template_folder()
    print(f"Copying deploy extras from {template_folder.resolve()} into {folder.resolve()}:\n")
    copy_template_extras(folder, template_folder, api_base, game_url)

    print(f"\nApplying URLs from setup/urls.ini:\n")
    print(f"  api_base = {api_base}")
    print(f"  game_url = {game_url}\n")
    fill_urls_in_export_html(folder, api_base, game_url)
    verify_no_placeholders_left(folder)

    print("\nDone. export/ is ready to upload to Cloudflare Pages.")


if __name__ == "__main__":
    main()